/**
 * Static seed data matching the WPGraphQL response shape.
 * Powers the site when NEXT_PUBLIC_WP_API_URL is not set.
 *
 * Prices sourced directly from thainigiri.com/discover-our-menu/.
 * Thai Entrees use protein-based pricing: chicken/pork/tofu/veg $18,
 * beef $19, shrimp $20, duck $26, salmon $27, combo $23.
 */
import type { MenuItem, SiteInfo } from "./types";

export const SITE_INFO: SiteInfo = {
  name: "Thai Nigiri",
  tagline: "Where Thailand Meets Japan",
  address: "209 N 1st Avenue, Sandpoint, ID 83864",
  phone: "(208) 265-2587",
  orderUrl: "https://order.spoton.com/so-thai-nigiri-restaurant-21928/sandpoint-id/675c9438abe91faea7628646",
  facebookUrl: "https://www.facebook.com/thainigirisandpoint",
  hours: [
    { days: "Monday – Wednesday", lunch: "11:30 am – 2:30 pm", dinner: "4:00 pm – 8:00 pm" },
    { days: "Thursday – Saturday", lunch: "11:30 am – 2:30 pm", dinner: "4:00 pm – 8:30 pm" },
    { days: "Sunday",              lunch: "Closed",              dinner: "Closed"              },
  ],
};

// Thai entree protein pricing note — appended to descriptions
const THAI_PRICE_NOTE =
  "Chicken, pork, tofu, or vegetables $18 · Beef $19 · Shrimp $20 · Duck $26 · Salmon $27 · Combo $23.";

export const MENU_ITEMS: MenuItem[] = [

  // ── Starters ──────────────────────────────────────────────────────────────
  {
    slug: "crab-rangoon",
    title: "Crab Rangoon (6)",
    content: "Crab meat, cream cheese, and onions in a wonton wrapper. Deep fried and served with plum sauce.",
    price: 10, isFeatured: false,
    category: { slug: "starters", name: "Starters" },
    imageUrl: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&q=80",
  },
  {
    slug: "fried-tofu",
    title: "Fried Tofu (6)",
    content: "Crispy fried tofu, served with plum sauce and peanuts on top.",
    price: 7.50, isFeatured: false,
    category: { slug: "starters", name: "Starters" },
  },
  {
    slug: "shrimp-in-a-blanket",
    title: "Shrimp in a Blanket (4)",
    content: "Deep fried shrimp wrapped in spring roll skin, served with plum sauce.",
    price: 11, isFeatured: false,
    category: { slug: "starters", name: "Starters" },
  },
  {
    slug: "shrimp-tempura-app",
    title: "Shrimp Tempura (6)",
    content: "Battered fried shrimp, served with plum and tempura sauce.",
    price: 12, isFeatured: false,
    category: { slug: "starters", name: "Starters" },
  },
  {
    slug: "gyoza",
    title: "Gyoza (6)",
    content: "Deep fried Japanese-style chicken pot stickers served with tempura sauce.",
    price: 8.50, isFeatured: false,
    category: { slug: "starters", name: "Starters" },
    imageUrl: "https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=600&q=80",
  },
  {
    slug: "edamame",
    title: "Edamame",
    content: "Steamed green soybeans with salt.",
    price: 6, isFeatured: false,
    category: { slug: "starters", name: "Starters" },
  },
  {
    slug: "spicy-edamame",
    title: "Spicy Edamame",
    content: "Steamed green soybeans with spicy seasoning.",
    price: 7.50, isFeatured: false,
    category: { slug: "starters", name: "Starters" },
  },
  {
    slug: "jalapeno-bomb",
    title: "Jalapeño Bomb (8)",
    content: "Deep-fried jalapeño, cream cheese, and spicy tuna. Served with yum yum, eel sauce, and sriracha.",
    price: 10.50, isFeatured: false,
    category: { slug: "starters", name: "Starters" },
  },
  {
    slug: "spirit-bomb",
    title: "Spirit Bomb (8)",
    content: "Deep fried avocado and crab meat on top of salad with special sauce.",
    price: 14, isFeatured: false,
    category: { slug: "starters", name: "Starters" },
  },
  {
    slug: "three-combo-appetizer",
    title: "Three Combo Appetizer",
    content: "Crab rangoons (3), gyozas (3), and jalapeño bomb (4 pcs). No substitutions.",
    price: 14.50, isFeatured: false,
    category: { slug: "starters", name: "Starters" },
  },
  {
    slug: "four-combo-appetizer",
    title: "Four Combo Appetizer",
    content: "Spring rolls (2), crab rangoons (2), jalapeño bomb (4 pcs), and shrimp in a blanket (2). No substitutions.",
    price: 16, isFeatured: false,
    category: { slug: "starters", name: "Starters" },
  },

  // ── Thai Entrees ──────────────────────────────────────────────────────────
  // Noodles
  {
    slug: "pad-thai",
    title: "Pad Thai",
    content: `Thin rice noodles with choice of meat, eggs, bean sprouts, scallions, and crushed peanuts with house Pad Thai sauce. ${THAI_PRICE_NOTE}`,
    price: 18, priceDisplay: "From $18", isFeatured: false,
    category: { slug: "thai-entrees", name: "Thai Entrees" },
    imageUrl: "https://images.unsplash.com/photo-1555126634-323283e090fa?w=600&q=80",
  },
  {
    slug: "pad-se-ew",
    title: "Pad Se-ew",
    content: `Stir fried flat rice noodles with choice of meat, eggs, broccoli, and carrots with Thai sweet soy sauce. ${THAI_PRICE_NOTE}`,
    price: 18, priceDisplay: "From $18", isFeatured: false,
    category: { slug: "thai-entrees", name: "Thai Entrees" },
  },
  {
    slug: "drunken-noodle",
    title: "Drunken Noodle",
    content: `Stir fried flat rice noodles with choice of meat, onions, bell peppers, bamboo shoots, and basil leaves with chili basil sauce. ${THAI_PRICE_NOTE}`,
    price: 18, priceDisplay: "From $18", isFeatured: false,
    category: { slug: "thai-entrees", name: "Thai Entrees" },
  },
  {
    slug: "pad-woon-sen",
    title: "Pad Woon-sen",
    content: `Stir fried glass noodles with eggs, choice of meat, green onions, onions, and mixed vegetables with Thai sauce. ${THAI_PRICE_NOTE}`,
    price: 18, priceDisplay: "From $18", isFeatured: false,
    category: { slug: "thai-entrees", name: "Thai Entrees" },
  },
  // Curries
  {
    slug: "red-curry",
    title: "Red Curry",
    content: `Red curry with a choice of meat, coconut milk, bell peppers, bamboo shoots, carrots, and basil leaves. ${THAI_PRICE_NOTE}`,
    price: 18, priceDisplay: "From $18", isFeatured: false,
    category: { slug: "thai-entrees", name: "Thai Entrees" },
    imageUrl: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=600&q=80",
  },
  {
    slug: "green-curry",
    title: "Green Curry",
    content: `Green curry with a choice of meat, coconut milk, bell peppers, bamboo shoots, carrots, peas, and basil leaves. ${THAI_PRICE_NOTE}`,
    price: 18, priceDisplay: "From $18", isFeatured: false,
    category: { slug: "thai-entrees", name: "Thai Entrees" },
  },
  {
    slug: "yellow-curry",
    title: "Yellow Curry",
    content: `Yellow curry with a choice of meat, coconut milk, pineapples, onions, potatoes, and carrots. ${THAI_PRICE_NOTE}`,
    price: 18, priceDisplay: "From $18", isFeatured: false,
    category: { slug: "thai-entrees", name: "Thai Entrees" },
  },
  {
    slug: "panang-curry",
    title: "Panang Curry",
    content: `Thai panang curry with a choice of meat, coconut milk, peanuts, peas, carrots, and kaffir lime leaves on a bed of steamed mixed vegetables. ${THAI_PRICE_NOTE}`,
    price: 18, priceDisplay: "From $18", isFeatured: false,
    category: { slug: "thai-entrees", name: "Thai Entrees" },
  },
  {
    slug: "duck-curry",
    title: "Duck Curry",
    content: "Roasted duck breast in red coconut curry with lychee, pineapple, tomatoes, and Thai basil. Served with jasmine rice.",
    price: 26, isFeatured: true,
    category: { slug: "thai-entrees", name: "Thai Entrees" },
    imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554?w=600&q=80",
  },
  {
    slug: "mango-tango",
    title: "Mango Tango",
    content: `Crispy tofu or shrimp tossed in a house mango sauce with bell peppers, snap peas, and Thai basil. Served with jasmine rice. ${THAI_PRICE_NOTE}`,
    price: 18, priceDisplay: "From $18", isFeatured: true,
    category: { slug: "thai-entrees", name: "Thai Entrees" },
    imageUrl: "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=600&q=80",
  },
  // Stir-Fry
  {
    slug: "sweet-basil",
    title: "Sweet Basil",
    content: `Stir fried choice of meat, carrots, onions, bell peppers, and basil with chili basil sauce. ${THAI_PRICE_NOTE}`,
    price: 18, priceDisplay: "From $18", isFeatured: false,
    category: { slug: "thai-entrees", name: "Thai Entrees" },
  },
  {
    slug: "lava",
    title: "Lava",
    content: `Stir fried choice of meat, carrots, onions, scallion, broccoli, mushroom in spicy Thai sauce. ${THAI_PRICE_NOTE}`,
    price: 18, priceDisplay: "From $18", isFeatured: false,
    category: { slug: "thai-entrees", name: "Thai Entrees" },
  },
  {
    slug: "cashew-nut",
    title: "Cashew Nut",
    content: `Stir fried choice of meat, carrots, onions, celery, bell peppers, and cashews in spicy Thai sauce. ${THAI_PRICE_NOTE}`,
    price: 18, priceDisplay: "From $18", isFeatured: false,
    category: { slug: "thai-entrees", name: "Thai Entrees" },
  },
  {
    slug: "mix-vegetables",
    title: "Mix Vegetables",
    content: `Stir fried choice of meat and mixed vegetables in Thai sauce. ${THAI_PRICE_NOTE}`,
    price: 18, priceDisplay: "From $18", isFeatured: false,
    category: { slug: "thai-entrees", name: "Thai Entrees" },
  },
  {
    slug: "rama",
    title: "Rama",
    content: `Sauteed choice of meat with peanut sauce, mixed vegetables, and pineapples topped with ground peanuts and cilantro. ${THAI_PRICE_NOTE}`,
    price: 18, priceDisplay: "From $18", isFeatured: false,
    category: { slug: "thai-entrees", name: "Thai Entrees" },
  },
  {
    slug: "garlic-and-pepper",
    title: "Garlic and Pepper",
    content: `Stir fried choice of meat with garlic and pepper sauce, on a bed of mixed vegetables. ${THAI_PRICE_NOTE}`,
    price: 18, priceDisplay: "From $18", isFeatured: false,
    category: { slug: "thai-entrees", name: "Thai Entrees" },
  },
  {
    slug: "broccoli",
    title: "Broccoli",
    content: `Stir fried choice of meat with broccoli and carrot in Thai sauce. ${THAI_PRICE_NOTE}`,
    price: 18, priceDisplay: "From $18", isFeatured: false,
    category: { slug: "thai-entrees", name: "Thai Entrees" },
  },
  {
    slug: "ginger-delight",
    title: "Ginger Delight",
    content: `Stir fried choice of meat with ginger, onion, baby corn, celery, mushroom, and carrot in Thai sauce. ${THAI_PRICE_NOTE}`,
    price: 18, priceDisplay: "From $18", isFeatured: false,
    category: { slug: "thai-entrees", name: "Thai Entrees" },
  },
  {
    slug: "sweet-and-sour",
    title: "Sweet & Sour",
    content: `Stir fried choice of meat with onion, bell pepper, carrot, and pineapple in sweet & sour sauce. ${THAI_PRICE_NOTE}`,
    price: 18, priceDisplay: "From $18", isFeatured: false,
    category: { slug: "thai-entrees", name: "Thai Entrees" },
  },
  // Rice
  {
    slug: "thai-fried-rice",
    title: "Thai Fried Rice",
    content: `Stir fried rice, eggs, and onions with a choice of meat, topped with scallions and cilantro. ${THAI_PRICE_NOTE}`,
    price: 18, priceDisplay: "From $18", isFeatured: false,
    category: { slug: "thai-entrees", name: "Thai Entrees" },
  },
  {
    slug: "basil-fried-rice",
    title: "Basil Fried Rice",
    content: `Stir fried choice of meat with rice, eggs, basil, bell peppers, onions, and chili basil sauce, topped with scallions. ${THAI_PRICE_NOTE}`,
    price: 18, priceDisplay: "From $18", isFeatured: false,
    category: { slug: "thai-entrees", name: "Thai Entrees" },
  },
  {
    slug: "japanese-stir-fry",
    title: "Japanese Stir-Fry",
    content: `Stir fried choice of meat, mixed vegetables, bamboo, and scallions in Japanese-styled sauce. ${THAI_PRICE_NOTE}`,
    price: 18, priceDisplay: "From $18", isFeatured: false,
    category: { slug: "thai-entrees", name: "Thai Entrees" },
  },
  {
    slug: "pineapple-fried-rice",
    title: "Pineapple Fried Rice",
    content: "Stir fried rice, shrimp, chicken, eggs, peas and carrots, green onions, onions, cashews, and pineapples.",
    price: 22, isFeatured: false,
    category: { slug: "thai-entrees", name: "Thai Entrees" },
  },

  // ── House Special Rolls ────────────────────────────────────────────────────
  {
    slug: "dancing-salmon",
    title: "Dancing Salmon",
    content: "Fresh Atlantic salmon, cucumber, avocado, topped with seared salmon, jalapeño, and our house spicy mayo.",
    price: 18, isFeatured: true,
    category: { slug: "house-special-rolls", name: "House Special Rolls" },
    imageUrl: "https://images.unsplash.com/photo-1648146207997-8a3ad0d00b97?w=600&q=80",
  },
  {
    slug: "avocado-roll",
    title: "Avocado Roll",
    content: "Crab and cucumbers topped with avocado.",
    price: 12.50, isFeatured: false,
    category: { slug: "house-special-rolls", name: "House Special Rolls" },
  },
  {
    slug: "baked-salmon-roll",
    title: "Baked Salmon",
    content: "Crab and avocado topped with baked salmon, yum yum, and eel sauce.",
    price: 14.75, isFeatured: false,
    category: { slug: "house-special-rolls", name: "House Special Rolls" },
    imageUrl: "https://images.unsplash.com/photo-1617196034183-421b4040ed20?w=600&q=80",
  },
  {
    slug: "spicy-baked-yellowtail",
    title: "Spicy Baked Yellowtail",
    content: "Crab and avocado topped with spicy baked yellowtail, spicy mayo, yum yum, and eel sauce.",
    price: 14.75, isFeatured: false,
    category: { slug: "house-special-rolls", name: "House Special Rolls" },
  },
  {
    slug: "japanese-lasagna",
    title: "Japanese Lasagna",
    content: "Crab, avocado, cream cheese topped with baked crab.",
    price: 13.75, isFeatured: false,
    category: { slug: "house-special-rolls", name: "House Special Rolls" },
  },
  {
    slug: "alaska-roll",
    title: "Alaska Roll",
    content: "Crab, avocado, cucumbers topped with salmon, lemon, tobiko, and green onions.",
    price: 15.25, isFeatured: false,
    category: { slug: "house-special-rolls", name: "House Special Rolls" },
  },
  {
    slug: "hawaiian-roll",
    title: "Hawaiian Roll",
    content: "Crab, avocado, cucumbers topped with tuna, masago, and green onions.",
    price: 15.25, isFeatured: false,
    category: { slug: "house-special-rolls", name: "House Special Rolls" },
  },
  {
    slug: "rainbow-roll",
    title: "Rainbow Roll",
    content: "Crab, avocado, cucumbers topped with tuna, salmon, white fish, shrimp, and avocado.",
    price: 16.25, isFeatured: false,
    category: { slug: "house-special-rolls", name: "House Special Rolls" },
    imageUrl: "https://images.unsplash.com/photo-1562802378-063ec186a863?w=600&q=80",
  },
  {
    slug: "rocky-mountain",
    title: "Rocky Mountain",
    content: "Crab, avocado, cucumbers topped with seaweed tempura and spicy tuna.",
    price: 15.25, isFeatured: false,
    category: { slug: "house-special-rolls", name: "House Special Rolls" },
  },
  {
    slug: "green-monster",
    title: "Green Monster",
    content: "Spicy tuna and cucumbers topped with avocado.",
    price: 14.25, isFeatured: false,
    category: { slug: "house-special-rolls", name: "House Special Rolls" },
  },
  {
    slug: "super-dragon-roll",
    title: "Super Dragon Roll (10)",
    content: "Crab, spicy tuna, and jalapeño topped with eel.",
    price: 20, isFeatured: false,
    category: { slug: "house-special-rolls", name: "House Special Rolls" },
  },
  {
    slug: "tuna-killer-roll",
    title: "Tuna Killer Roll",
    content: "Spicy tuna and cucumber topped with tuna, spicy mayo, and sriracha.",
    price: 15.75, isFeatured: false,
    category: { slug: "house-special-rolls", name: "House Special Rolls" },
  },
  {
    slug: "salmon-killer",
    title: "Salmon Killer",
    content: "Spicy salmon and cucumbers topped with salmon, spicy mayo, and sriracha.",
    price: 15.75, isFeatured: false,
    category: { slug: "house-special-rolls", name: "House Special Rolls" },
  },
  {
    slug: "unagi-bomb",
    title: "Unagi Bomb",
    content: "Spicy tuna, jalapeño tempura, cream cheese topped with eel and sriracha.",
    price: 16.75, isFeatured: false,
    category: { slug: "house-special-rolls", name: "House Special Rolls" },
  },
  {
    slug: "spider-man-roll",
    title: "Spider Man Roll (6)",
    content: "Spicy tuna, soft shell crab tempura, cucumbers, avocado, romaine topped with eel.",
    price: 14.75, isFeatured: false,
    category: { slug: "house-special-rolls", name: "House Special Rolls" },
  },
  {
    slug: "ninja-roll",
    title: "Ninja Roll",
    content: "Shrimp tempura, crab, cucumbers topped with eel and avocado.",
    price: 16.75, isFeatured: false,
    category: { slug: "house-special-rolls", name: "House Special Rolls" },
  },
  {
    slug: "sandpoint-roll",
    title: "Sandpoint Roll",
    content: "Salmon, cream cheese, avocado, deep-fried, topped with seared scallops.",
    price: 16.75, isFeatured: false,
    category: { slug: "house-special-rolls", name: "House Special Rolls" },
  },

  // ── Sushi Rolls (Maki) ────────────────────────────────────────────────────
  {
    slug: "harvest-roll",
    title: "Harvest Roll",
    content: "Tempura sweet potato, cream cheese, and cucumber topped with avocado and a drizzle of teriyaki glaze.",
    price: 10, isFeatured: false,
    category: { slug: "sushi-rolls", name: "Sushi Rolls" },
    imageUrl: "https://images.unsplash.com/photo-1611143669185-af224c5e3252?w=600&q=80",
  },
  {
    slug: "tuna-maki",
    title: "Tuna Maki",
    content: "Fresh tuna wrapped in seasoned rice and nori.",
    price: 6.50, isFeatured: false,
    category: { slug: "sushi-rolls", name: "Sushi Rolls" },
  },
  {
    slug: "salmon-maki",
    title: "Salmon Maki",
    content: "Fresh salmon wrapped in seasoned rice and nori.",
    price: 6.50, isFeatured: false,
    category: { slug: "sushi-rolls", name: "Sushi Rolls" },
  },
  {
    slug: "yellowtail-maki",
    title: "Yellowtail Maki",
    content: "Fresh yellowtail wrapped in seasoned rice and nori.",
    price: 6.50, isFeatured: false,
    category: { slug: "sushi-rolls", name: "Sushi Rolls" },
  },
  {
    slug: "cucumber-maki",
    title: "Cucumber Maki",
    content: "Crisp cucumber wrapped in seasoned rice and nori.",
    price: 5.25, isFeatured: false,
    category: { slug: "sushi-rolls", name: "Sushi Rolls" },
  },
  {
    slug: "avocado-maki",
    title: "Avocado Maki",
    content: "Creamy avocado wrapped in seasoned rice and nori.",
    price: 5.25, isFeatured: false,
    category: { slug: "sushi-rolls", name: "Sushi Rolls" },
  },
  {
    slug: "california",
    title: "California Roll",
    content: "Crab, avocado, and cucumbers.",
    price: 8.50, isFeatured: false,
    category: { slug: "sushi-rolls", name: "Sushi Rolls" },
  },
  {
    slug: "spicy-tuna",
    title: "Spicy Tuna Roll",
    content: "Spicy tuna with cucumbers.",
    price: 9.50, isFeatured: false,
    category: { slug: "sushi-rolls", name: "Sushi Rolls" },
  },
  {
    slug: "spicy-yellowtail",
    title: "Spicy Yellowtail Roll",
    content: "Spicy yellowtail with cucumbers and sriracha.",
    price: 9.50, isFeatured: false,
    category: { slug: "sushi-rolls", name: "Sushi Rolls" },
  },
  {
    slug: "spicy-salmon",
    title: "Spicy Salmon Roll",
    content: "Spicy salmon with cucumbers and sriracha.",
    price: 9.50, isFeatured: false,
    category: { slug: "sushi-rolls", name: "Sushi Rolls" },
  },
  {
    slug: "philadelphia",
    title: "Philadelphia Roll",
    content: "Salmon, crab, cucumbers, avocado, and cream cheese.",
    price: 10, isFeatured: false,
    category: { slug: "sushi-rolls", name: "Sushi Rolls" },
  },
  {
    slug: "shrimp-tempura-roll",
    title: "Shrimp Tempura Roll",
    content: "Shrimp tempura, crab, cucumbers, avocado, yum yum, and eel sauce.",
    price: 10, isFeatured: false,
    category: { slug: "sushi-rolls", name: "Sushi Rolls" },
  },
  {
    slug: "tempura-ca",
    title: "Tempura CA (10)",
    content: "Crab and avocado, deep-fried whole roll with yum yum and eel sauce.",
    price: 12.50, isFeatured: false,
    category: { slug: "sushi-rolls", name: "Sushi Rolls" },
  },
  {
    slug: "spicy-tuna-tempura",
    title: "Spicy Tuna Tempura (10)",
    content: "Spicy tuna and avocado, deep-fried whole roll with yum yum and eel sauce.",
    price: 13.50, isFeatured: false,
    category: { slug: "sushi-rolls", name: "Sushi Rolls" },
  },
  {
    slug: "asparagus-tempura",
    title: "Asparagus Tempura (5)",
    content: "Asparagus tempura, cucumbers, and avocado with yum yum and eel sauce.",
    price: 8.50, isFeatured: false,
    category: { slug: "sushi-rolls", name: "Sushi Rolls" },
  },

  // ── Nigiri & Sashimi ──────────────────────────────────────────────────────
  {
    slug: "hamachi-karma",
    title: "Hamachi Karma",
    content: "Yellowtail, jalapeño, and ponzu sauce. Clean, bright, and beautifully simple.",
    price: 13, isFeatured: true,
    category: { slug: "nigiri-sashimi", name: "Nigiri & Sashimi" },
    imageUrl: "https://images.unsplash.com/photo-1562802378-063ec186a863?w=600&q=80",
  },
  {
    slug: "hamachi-nigiri",
    title: "Hamachi Nigiri (2 pc)",
    content: "Fresh yellowtail over hand-pressed seasoned rice.",
    price: 7, isFeatured: false,
    category: { slug: "nigiri-sashimi", name: "Nigiri & Sashimi" },
  },
  {
    slug: "maguro-nigiri",
    title: "Maguro Nigiri (2 pc)",
    content: "Fresh tuna over hand-pressed seasoned rice.",
    price: 7, isFeatured: false,
    category: { slug: "nigiri-sashimi", name: "Nigiri & Sashimi" },
  },
  {
    slug: "scallop-nigiri",
    title: "Scallop Nigiri (2 pc)",
    content: "Fresh scallop over hand-pressed seasoned rice.",
    price: 7, isFeatured: false,
    category: { slug: "nigiri-sashimi", name: "Nigiri & Sashimi" },
  },
  {
    slug: "ebi-nigiri",
    title: "Ebi Nigiri (2 pc)",
    content: "Shrimp over hand-pressed seasoned rice.",
    price: 5.50, isFeatured: false,
    category: { slug: "nigiri-sashimi", name: "Nigiri & Sashimi" },
  },
  {
    slug: "kani-nigiri",
    title: "Kani Nigiri (2 pc)",
    content: "Crab stick over hand-pressed seasoned rice.",
    price: 5, isFeatured: false,
    category: { slug: "nigiri-sashimi", name: "Nigiri & Sashimi" },
  },
  {
    slug: "tobiko-nigiri",
    title: "Tobiko Nigiri (2 pc)",
    content: "Flying fish roe over hand-pressed seasoned rice.",
    price: 6.50, isFeatured: false,
    category: { slug: "nigiri-sashimi", name: "Nigiri & Sashimi" },
  },
  {
    slug: "unagi-nigiri",
    title: "Unagi Nigiri (2 pc)",
    content: "Grilled freshwater eel over hand-pressed seasoned rice.",
    price: 7.50, isFeatured: false,
    category: { slug: "nigiri-sashimi", name: "Nigiri & Sashimi" },
  },
  {
    slug: "sashimi",
    title: "Sashimi (5 pc)",
    content: "Five slices of one variety — tuna, salmon, yellowtail, or scallop.",
    price: 13, isFeatured: false,
    category: { slug: "nigiri-sashimi", name: "Nigiri & Sashimi" },
  },
  {
    slug: "sushi-sampler",
    title: "Sushi Sampler",
    content: "One piece each of tuna, salmon, yellowtail, and ebi nigiri.",
    price: 13, isFeatured: false,
    category: { slug: "nigiri-sashimi", name: "Nigiri & Sashimi" },
  },
  {
    slug: "sashimi-sampler",
    title: "Sashimi Sampler (9 pc)",
    content: "Three pieces each of tuna, salmon, and yellowtail.",
    price: 23, isFeatured: false,
    category: { slug: "nigiri-sashimi", name: "Nigiri & Sashimi" },
  },
  {
    slug: "sushi-deluxe",
    title: "Sushi Deluxe",
    content: "Two pieces each of tuna, salmon, yellowtail nigiri plus two special rolls.",
    price: 50, isFeatured: false,
    category: { slug: "nigiri-sashimi", name: "Nigiri & Sashimi" },
  },
  {
    slug: "sashimi-deluxe",
    title: "Sashimi Deluxe",
    content: "Tuna, salmon, yellowtail, scallop, and albacore with miso soup and salad.",
    price: 50, isFeatured: false,
    category: { slug: "nigiri-sashimi", name: "Nigiri & Sashimi" },
  },

  // ── Chef's Specials (featured on original homepage) ───────────────────────
  {
    slug: "chashu-don",
    title: "Chashu Don",
    content: "Slow-braised pork belly over steamed rice with soft-boiled egg, pickled ginger, nori, and house tare.",
    price: 15, isFeatured: true,
    category: { slug: "chefs-specials", name: "Chef's Specials" },
    imageUrl: "https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=600&q=80",
  },
  {
    slug: "unagi-don",
    title: "Unagi Don",
    content: "Grilled freshwater eel over steamed rice with house unagi sauce, sesame, and cucumber.",
    price: 25, isFeatured: false,
    category: { slug: "chefs-specials", name: "Chef's Specials" },
  },
  {
    slug: "bento-box",
    title: "Bento Box",
    content: "Your choice of protein with miso soup, house salad, steamed rice, gyoza, and seasonal vegetable. Ask your server for today's selections.",
    price: 25, isFeatured: false,
    category: { slug: "chefs-specials", name: "Chef's Specials" },
  },
  {
    slug: "tom-yum-ramen",
    title: "Tom Yum Ramen",
    content: "House-made broth blending Thai tom yum with Japanese tonkotsu. Topped with shrimp, mushrooms, lemongrass, and soft-boiled egg.",
    price: 15, isFeatured: false,
    category: { slug: "chefs-specials", name: "Chef's Specials" },
    imageUrl: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&q=80",
  },
];

export const FEATURED_ITEMS = MENU_ITEMS.filter((item) => item.isFeatured);

export const MENU_CATEGORIES = [
  { slug: "starters",           name: "Starters"           },
  { slug: "thai-entrees",       name: "Thai Entrees"       },
  { slug: "house-special-rolls",name: "House Special Rolls"},
  { slug: "sushi-rolls",        name: "Sushi Rolls"        },
  { slug: "nigiri-sashimi",     name: "Nigiri & Sashimi"   },
  { slug: "chefs-specials",     name: "Chef's Specials"    },
];
